// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzS7NA2I1nJGSFytPSZsdDKQF0CCYYaSQ',
    appId: '1:34934094678:web:422c8d3089527c7ed3f4f7',
    messagingSenderId: '34934094678',
    projectId: 'flutter-ai-playground-2e553',
    authDomain: 'flutter-ai-playground-2e553.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-2e553.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIELjUXBzFWB9kR4udLI1MlApctXJuLiM',
    appId: '1:34934094678:android:b0b43b09757b9d5dd3f4f7',
    messagingSenderId: '34934094678',
    projectId: 'flutter-ai-playground-2e553',
    storageBucket: 'flutter-ai-playground-2e553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGeWl-2vkiR48GgV0y6zoKuij6197egM',
    appId: '1:34934094678:ios:383fc2c3ca5b8169d3f4f7',
    messagingSenderId: '34934094678',
    projectId: 'flutter-ai-playground-2e553',
    storageBucket: 'flutter-ai-playground-2e553.firebasestorage.app',
    iosBundleId: 'com.example.societyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoGeWl-2vkiR48GgV0y6zoKuij6197egM',
    appId: '1:34934094678:ios:383fc2c3ca5b8169d3f4f7',
    messagingSenderId: '34934094678',
    projectId: 'flutter-ai-playground-2e553',
    storageBucket: 'flutter-ai-playground-2e553.firebasestorage.app',
    iosBundleId: 'com.example.societyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzS7NA2I1nJGSFytPSZsdDKQF0CCYYaSQ',
    appId: '1:34934094678:web:a5bff873060fe0b3d3f4f7',
    messagingSenderId: '34934094678',
    projectId: 'flutter-ai-playground-2e553',
    authDomain: 'flutter-ai-playground-2e553.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-2e553.firebasestorage.app',
  );
}
