import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:societyhub/screens/admin/AdminManageResidentsScreen.dart';
import 'firebase_options.dart'; // ✅ generated by FlutterFire CLI

import 'package:societyhub/screens/admin/admin_dashboard.dart';
import 'package:societyhub/screens/admin/admin_track_tasks.dart';
import 'package:societyhub/screens/admin/managerequesttaskscreen.dart';

import 'package:societyhub/screens/resident/request_tracking.dart';
import 'package:societyhub/screens/resident/resident_dashboard.dart';
import 'package:societyhub/screens/resident/service_request_form.dart';

import 'package:societyhub/screens/roleselectionscreen.dart';
import 'package:societyhub/screens/signup_screen.dart';
import 'package:societyhub/screens/worker/worker_dashboard.dart';
import 'package:societyhub/screens/worker/worker_task_list.dart';

import 'screens/login_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Flutter binding

  // ✅ Firebase initialize with options (required for Web)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(SocietyHubApp());
}

class SocietyHubApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SocietyHub',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: Colors.grey[100],
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.blue,
          elevation: 2,
        ),
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          selectedItemColor: Colors.blue,
          unselectedItemColor: Colors.grey,
        ),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const RoleSelectionScreen(),
        '/login': (context) => LoginScreen(),
        '/signup': (context) => const SignupScreen(),

        // Resident
        '/resident_dashboard': (context) {
  final args = ModalRoute.of(context)!.settings.arguments;
  if (args == null || args is! String) {
    // fallback if no ID provided
    return const Scaffold(
      body: Center(child: Text('Resident ID missing!')),
    );
  }
  return ResidentDashboardScreen(residentId: args);
},

        '/service_request_form': (context) => ServiceRequestForm(residentId: '',),
        '/request_tracking': (context) => const RequestTracking(residentId: '',),

        // Worker
        '/worker_dashboard': (context) => const WorkerDashboardScreen(),
        '/worker_task_list': (context) => const WorkerTaskListScreen(),

        // Admin
        '/admin_dashboard': (context) => const AdminDashboardScreen(),
        '/admin_track_tasks': (context) => const AdminTrackTasks(),
        '/manage_request_task': (context) => const ManageRequestTaskScreen(),
        '/admin_manage_residents': (context) => const AdminManageResidentsScreen(),
      },
    );
  }
}
